### ISSUE TITLE
This repository should point to azureml-examples for a more interesting set of use cases

### ISSUE THREAD

**Issue by dkmiller** [Azure/azureml-template#21]
This repo gives a great, clean, example of how to use GitHub actions to automate MLOps.

Users will be interested in more interesting / deep examples (e.g., something more interesting than scikit-learn). This repo should point to azureml-examples for those.

**Comment by lostmygithubaccount** [comment]
it's in the Reference section, should it be somewhere else in the README?

**Comment by dkmiller** [comment]
Oops, my bad for not noticing that.
